package com.swart.scryfallfluentapi.model;

/**
 *
 * @author jake swart
 *
 */
public enum SetDBEnum {
  GameNight2019("gn2"), PoniesTheGalloping("ptg"), ThroneOfEldrainePromos("peld"), ThroneOfEldraine("eld"),
  ThroneOfEldraineTokens("teld"), Commander2019OverSized("oc19"), Commander2019("c19"), SanDiegoComicCon2019("ps19"),
  CoreSet2020Promos("pm20"), CoreSet2020Tokens("tm20"), M20PromoPacks("ppp1"), CoreSet2020("m20"),
  SignatureSpellbookGideon("ss2"), ModernHorizonsPromos("pmh1"), ModernHorizons("mh1"), ModernHorizonsTokens("tmh1"),
  WaroftheSparkTokens("twar"), WaroftheSpark("war"), JudgeGiftCards2019("j19"), WaroftheSparkPromos("pwar"),
  RNARavnicaWeekend("prw2"), RNAGuildKit("gk2"), RNAGuildKitTokens("tgk2"), RavnicaAllegiancePromos("prna"),
  RavnicaAllegiance("rna"), RavnicaAllegianceTokens("trna"), MagicFest2019("pf19"), PlanechaseAnthologyPlanes("opca"),
  UltimateBoxTopper("puma"), UltimateMasters("uma"), UltimateMastersTokens("tuma"), GameNight("gnt"),
  M19GiftPack("g18"), GRNGuildKitTokens("tgk1"), GRNGuildKit("gk1"), GuildsofRavnicaPromos("pgrn"),
  GuildsofRavnicaTokens("tgrn"), GuildsofRavnica("grn"), GRNRavnicaWeekend("prwk"), MythicEditionTokens("tmed"),
  MythicEdition("med"), Commander2018Oversized("oc18"), Commander2018("c18"), Commander2018Tokens("tc18"),
  HeroesoftheRealm2017("htr17"), SanDiegoComicCon2018("ps18"), ArenaNewPlayerExperience("ana"), MTGArenaPromos("pana"),
  M19StandardShowdown("pss3"), CoreSet2019Promos("pm19"), CoreSet2019("m19"), CoreSet2019Tokens("tm19"),
  GlobalSeriesJiangYangguAndMuYanling("gs1"), SignatureSpellbookJace("ss1"), BattlebondPromos("pbbd"),
  Battlebond("bbd"), BattlebondTokens("tbbd"), CommanderAnthologyVolumeIITokens("tcm2"),
  CommanderAnthologyVolumeII("cm2"), DominariaTokens("tdom"), Dominaria("dom"), DominariaPromos("pdom"),
  DuelDecksElvesvsInventors("ddu"), DuelDecksElvesvsInventorsTokens("tddu"), Masters25("a25"), Masters25Tokens("ta25"),
  LunarNewYear2018("plny"), NationalsPromos("pnat"), RivalsofIxalanPromos("prix"), RivalsofIxalanTokens("trix"),
  RivalsofIxalan("rix"), JudgeGiftCards2018("j18"), FridayNightMagic2018("f18"), Unstable("ust"),
  IconicMastersTokens("tima"), XLNTreasureChest("pxtc"), FromtheVaultTransform("v17"), ExplorersofIxalan("e02"),
  IconicMasters("ima"), UnstableTokens("tust"), UnstablePromos("pust"), DuelDecksMerfolkvsGoblins("ddt"),
  DuelDecksMerfolkvsGoblinsTokens("tddt"), GiftPack2017("g17"), Ixalan("xln"), IxalanTokens("txln"),
  IxalanPromos("pxln"), XLNStandardShowdown("pss2"), HasCon2017("h17"), HeroesoftheRealm("htr"),
  ArchenemyNicolBolasTokens("te01"), Commander2017Oversized("oc17"), Commander2017("c17"), Commander2017Tokens("tc17"),
  SanDiegoComicCon2017("ps17"), HourofDevastation("hou"), HourofDevastationPromos("phou"),
  HourofDevastationTokens("thou"), ArchenemyNicolBolasSchemes("oe01"), ArchenemyNicolBolas("e01"),
  CommanderAnthologyTokens("tcma"), CommanderAnthology("cma"), Amonkhet("akh"), AmonkhetPromos("pakh"),
  AmonkhetTokens("takh"), AmonkhetInvocations("mp2"), WelcomeDeck2017("w17"), DuelDecksMindvsMight("dds"),
  DuelDecksMindvsMightTokens("tdds"), ModernMasters2017Tokens("tmm3"), ModernMasters2017("mm3"),
  AetherRevoltTokens("taer"), AetherRevolt("aer"), AetherRevoltPromos("paer"), LeagueTokens2017("l17"),
  JudgeGiftCards2017("j17"), FridayNightMagic2017("f17"), PlanechaseAnthology("pca"), PlanechaseAnthologyTokens("tpca"),
  TreasureChest("pz2"), Commander2016Oversized("oc16"), Commander2016("c16"), Commander2016Tokens("tc16"),
  SanDiegoComicCon2016("ps16"), Kaladesh("kld"), KaladeshTokens("tkld"), KaladeshPromos("pkld"),
  KaladeshInventions("mps"), DuelDecksNissavsObNixilis("ddr"), ConspiracyTaketheCrownTokens("tcn2"),
  ConspiracyTaketheCrown("cn2"), FromtheVaultLore("v16"), EldritchMoonTokens("temn"), EldritchMoon("emn"),
  EldritchMoonPromos("pemn"), EternalMasters("ema"), EternalMastersTokens("tema"), ShadowsoverInnistradTokens("tsoi"),
  ShadowsoverInnistrad("soi"), ShadowsoverInnistradPromos("psoi"), WelcomeDeck2016("w16"),
  DuelDecksBlessedvsCursed("ddq"), OathoftheGatewatchTokens("togw"), OathoftheGatewatch("ogw"),
  OathoftheGatewatchPromos("pogw"), LeagueTokens2016("l16"), FridayNightMagic2016("f16"), JudgeGiftCards2016("j16"),
  LegendaryCubePrizePack("pz1"), Commander2015("c15"), Commander2015Tokens("tc15"), Commander2015Oversized("oc15"),
  BattleforZendikar("bfz"), BattleforZendikarTokens("tbfz"), BFZStandardSeries("pss1"), ZendikarExpeditions("exp"),
  BattleforZendikarPromos("pbfz"), DuelDecksZendikarvsEldrazi("ddp"), FromtheVaultAngels("v15"),
  MagicOriginsClashPack("cp3"), MagicOriginsPromos("pori"), MagicOrigins("ori"), MagicOriginsTokens("tori"),
  SanDiegoComicCon2015("ps15"), ModernMasters2015Tokens("tmm2"), ModernMasters2015("mm2"), TempestRemastered("tpr"),
  TarkirDragonfury("ptkdf"), DragonsofTarkirTokens("tdtk"), DragonsofTarkir("dtk"), DragonsofTarkirPromos("pdtk"),
  DuelDecksElspethvsKiora("ddo"), FateReforgedPromos("pfrf"), FateReforgedClashPack("cp2"), FateReforgedTokens("tfrf"),
  FateReforged("frf"), UginsFate("ugin"), LeagueTokens2015("l15"), JudgeGiftCards2015("j15"),
  FridayNightMagic2015("f15"), DuelDecksAnthologyJacevsChandraTokens("tjvc"),
  DuelDecksAnthologyDivinevsDemonicTokens("tdvd"), DuelDecksAnthologyGarrukvsLilianaTokens("tgvl"),
  DuelDecksAnthologyJacevsChandra("jvc"), DuelDecksAnthologyGarrukvsLiliana("gvl"),
  DuelDecksAnthologyElvesvsGoblinsTokens("tevg"), DuelDecksAnthologyDivinevsDemonic("dvd"),
  DuelDecksAnthologyElvesvsGoblins("evg"), Commander2014Oversized("oc14"), Commander2014Tokens("tc14"),
  Commander2014("c14"), KhansofTarkirTokens("tktk"), KhansofTarkir("ktk"), KhansofTarkirPromos("pktk"),
  DuelDecksSpeedvsCunning("ddn"), FromtheVaultAnnihilation("v14"), Magic2015ClashPack("cp1"), Magic2015("m15"),
  Magic2015Tokens("tm15"), Magic2015Promos("pm15"), M15PrereleaseChallenge("ppc1"), SanDiegoComicCon2014("ps14"),
  VintageMasters("vma"), Conspiracy("cns"), ConspiracyTokens("tcns"), ModernEventDeck2014Tokens("tmd1"),
  ModernEventDeck2014("md1"), DefeataGod("tdag"), JourneyintoNyx("jou"), JourneyintoNyxTokens("tjou"),
  JourneyintoNyxHerosPath("thp3"), JourneyintoNyxPromos("pjou"), DuelDecksJacevsVraskaTokens("tddm"),
  DuelDecksJacevsVraska("ddm"), BattletheHorde("tbth"), BornoftheGodsHerosPath("thp2"), BornoftheGods("bng"),
  BornoftheGodsTokens("tbng"), BornoftheGodsPromos("pbng"), DuelsofthePlaneswalkersPromos2014("pdp14"),
  IDWComics2014("pi14"), LeagueTokens2014("l14"), FridayNightMagic2014("f14"), JudgeGiftCards2014("j14"),
  Commander2013Oversized("oc13"), Commander2013("c13"), FacetheHydra("tfth"), Theros("ths"), TherosHerosPath("thp1"),
  TherosTokens("tths"), TherosPromos("pths"), DuelDecksHeroesvsMonstersTokens("tddl"), DuelDecksHeroesvsMonsters("ddl"),
  FromtheVaultTwenty("v13"), Magic2014Tokens("tm14"), Magic2014("m14"), Magic2014Promos("pm14"),
  SanDiegoComicCon2013("psdc"), ModernMastersTokens("tmma"), ModernMasters("mma"), DragonsMaze("dgm"),
  DragonsMazeTokens("tdgm"), DragonsMazePromos("pdgm"), WorldMagicCupQualifiers("pwcq"), DuelDecksSorinvsTibalt("ddk"),
  DuelDecksSorinvsTibaltTokens("tddk"), Gatecrash("gtc"), GatecrashTokens("tgtc"), GatecrashPromos("pgtc"),
  DuelsofthePlaneswalkersPromos2013("pdp13"), IDWComics2013("pi13"), LeagueTokens2013("l13"), JudgeGiftCards2013("j13"),
  FridayNightMagic2013("f13"), CommandersArsenalOversized("ocm1"), CommandersArsenal("cm1"), ReturntoRavnica("rtr"),
  ReturntoRavnicaPromos("prtr"), ReturntoRavnicaTokens("trtr"), DuelDecksIzzetvsGolgari("ddj"),
  DuelDecksIzzetvsGolgariTokens("tddj"), FromtheVaultRealms("v12"), Magic2013("m13"), Magic2013Tokens("tm13"),
  Magic2013Promos("pm13"), Planechase2012Planes("opc2"), Planechase2012("pc2"), AvacynRestoredTokens("tavr"),
  AvacynRestored("avr"), OpentheHelvault("phel"), AvacynRestoredPromos("pavr"), DuelDecksVenservsKothTokens("tddi"),
  DuelDecksVenservsKoth("ddi"), DarkAscension("dka"), DarkAscensionTokens("tdka"), DarkAscensionPromos("pdka"),
  IDWComics2012("pidw"), WizardsPlayNetwork2012("pwp12"), DuelsofthePlaneswalkersPromos2012("pdp12"),
  LeagueTokens2012("l12"), JudgeGiftCards2012("j12"), FridayNightMagic2012("f12"), PremiumDeckSeriesGraveborn("pd3"),
  InnistradTokens("tisd"), Innistrad("isd"), InnistradPromos("pisd"), DuelDecksAjanivsNicolBolas("ddh"),
  DuelDecksAjanivsNicolBolasTokens("tddh"), FromtheVaultLegends("v11"), Magic2012Tokens("tm12"), Magic2012("m12"),
  Magic2012Promos("pm12"), Commander2011Oversized("ocmd"), Commander2011("cmd"), Commander2011LaunchParty("pcmd"),
  DuelDecksMirrodinPurevsNewPhyrexia("td2"), NewPhyrexiaTokens("tnph"), NewPhyrexia("nph"), NewPhyrexiaPromos("pnph"),
  DuelDecksKnightsvsDragons("ddg"), DuelDecksKnightsvsDragonsTokens("tddg"), MirrodinBesiegedTokens("tmbs"),
  MirrodinBesieged("mbs"), MirrodinBesiegedPromos("pmbs"), MastersEditionIV("me4"), MagicPremiereShop2011("pmps11"),
  DuelsofthePlaneswalkersPromos2011("pdp11"), WizardsPlayNetwork2011("pwp11"), FridayNightMagic2011("f11"),
  Salvat2011("ps11"), JudgeGiftCards2011("g11"), MagicPlayerRewards2011("p11"), LegacyChampionship("olgc"),
  PremiumDeckSeriesFireandLightning("pd2"), MagicOnlineThemeDecks("td0"), ScarsofMirrodinTokens("tsom"),
  ScarsofMirrodin("som"), ScarsofMirrodinPromos("psom"), DuelDecksElspethvsTezzeret("ddf"),
  DuelDecksElspethvsTezzeretTokens("tddf"), FromtheVaultRelics("v10"), Magic2011Tokens("tm11"), Magic2011("m11"),
  Magic2011Promos("pm11"), ArchenemySchemes("oarc"), Archenemy("arc"), PromotionalSchemes("parc"),
  DuelsofthePlaneswalkers("dpa"), RiseoftheEldraziPromos("proe"), RiseoftheEldraziTokens("troe"),
  RiseoftheEldrazi("roe"), DuelDecksPhyrexiavstheCoalitionTokens("tdde"), DuelDecksPhyrexiavstheCoalition("dde"),
  WorldwakePromos("pwwk"), Worldwake("wwk"), WorldwakeTokens("twwk"), DuelsofthePlaneswalkersPromos2010("pdp10"),
  WizardsPlayNetwork2010("pwp10"), MagicPremiereShop2010("pmps10"), FridayNightMagic2010("f10"),
  MagicPlayerRewards2010("p10"), JudgeGiftCards2010("g10"), PremiumDeckSeriesSlivers("h09"),
  DuelDecksGarrukvsLiliana("ddd"), DuelDecksGarrukvsLilianaTokens("tddd"), ZendikarPromos("pzen"), Zendikar("zen"),
  ZendikarTokens("tzen"), MastersEditionIII("me3"), PlanechasePlanes("ohop"), Planechase("hop"),
  PromotionalPlanes("phop"), FromtheVaultExiled("v09"), Magic2010Tokens("tm10"), Magic2010("m10"),
  Magic2010Promos("pm10"), AlaraRebornTokens("tarb"), AlaraReborn("arb"), DuelDecksDivinevsDemonic("ddc"),
  DuelDecksDivinevsDemonicTokens("tddc"), URLConventionPromos("purl"), Conflux("con"), ConfluxTokens("tcon"),
  MiscellaneousBookPromos("pbok"), WizardsPlayNetwork2009("pwp09"), DuelsofthePlaneswalkersPromos2009("pdtp"),
  MagicPremiereShop2009("pmps09"), MagicPlayerRewards2009("p09"), FridayNightMagic2009("f09"),
  JudgeGiftCards2009("g09"), DuelDecksJacevsChandra("dd2"), DuelDecksJacevsChandraTokens("tdd2"),
  ShardsofAlaraTokens("tala"), ShardsofAlara("ala"), WizardsPlayNetwork2008("pwpn"), MastersEditionII("me2"),
  FromtheVaultDragons("drb"), Eventide("eve"), EventideTokens("teve"), ShadowmoorTokens("tshm"), Shadowmoor("shm"),
  FifteenthAnniversaryCards("p15a"), Morningtide("mor"), MorningtideTokens("tmor"), LaunchParties("plpa"),
  MagicPremiereShop2008("pmps08"), Gateway2008("pg08"), FridayNightMagic2008("f08"), JudgeGiftCards2008("g08"),
  MagicPlayerRewards2008("p08"), DuelDecksElvesvsGoblinsTokens("tdd1"), DuelDecksElvesvsGoblins("dd1"),
  LorwynTokens("tlrw"), Lorwyn("lrw"), MastersEdition("me1"), SummerofMagic("psum"), TenthEdition("10e"),
  TenthEditionPromos("p10e"), TenthEditionTokens("t10e"), FutureSight("fut"), GrandPrixPromos("pgpx"),
  ProTourPromos("ppro"), PlanarChaos("plc"), ResalePromos("pres"), Gateway2007("pg07"), MagicPremiereShop2007("pmps07"),
  MagicPlayerRewards2007("p07"), JudgeGiftCards2007("g07"), FridayNightMagic2007("f07"), HappyHolidays("hho"),
  TimeSpiral("tsp"), TimeSpiralTimeshifted("tsb"), ColdsnapTokens("tcsp"), Coldsnap("csp"), ColdsnapThemeDecks("cst"),
  Dissension("dis"), ChampsandStates("pcmp"), Guildpact("gpt"), ArenaLeague2006("pal06"),
  MagicPremiereShop2006("pmps06"), JuniorAPACSeries("pjas"), JudgeGiftCards2006("g06"), HachetteUK("phuk"),
  MagicPlayerRewards2006("p06"), Gateway2006("pgtw"), FridayNightMagic2006("f06"), TwoHeadedGiantTournament("p2hg"),
  RavnicaCityofGuilds("rav"), Salvat2005("psal"), NinthEdition("9ed"), SaviorsofKamigawa("sok"),
  BetrayersofKamigawa("bok"), MagicPremiereShop2005("pmps"), ArenaLeague2005("pal05"), JuniorSeriesEurope("pjse"),
  FridayNightMagic2005("f05"), JudgeGiftCards2005("g05"), MagicPlayerRewards2005("p05"), Unhinged("unh"),
  ChampionsofKamigawa("chk"), WorldChampionshipDecks2004("wc04"), FifthDawn("5dn"), Darksteel("dst"),
  ArenaLeague2004("pal04"), MagicPlayerRewards2004("p04"), JudgeGiftCards2004("g04"), FridayNightMagic2004("f04"),
  Mirrodin("mrd"), WorldChampionshipDecks2003("wc03"), EighthEdition("8ed"), ReleaseEvents("prel"), Scourge("scg"),
  Legions("lgn"), MagicOnlineAvatars("pmoa"), JapanJuniorTournament("pjjt"), ArenaLeague2003("pal03"),
  VintageChampionship("ovnt"), FridayNightMagic2003("f03"), MagicPlayerRewards2003("p03"), JudgeGiftCards2003("g03"),
  Onslaught("ons"), WorldChampionshipDecks2002("wc02"), HobbyJapanPromos("phj"), MagicOnlinePromos("prm"),
  Judgment("jud"), Torment("tor"), ArenaLeague2002("pal02"), JudgeGiftCards2002("g02"), MagicPlayerRewards2002("pr2"),
  FridayNightMagic2002("f02"), Deckmasters("dkm"), Odyssey("ody"), WorldChampionshipDecks2001("wc01"),
  Apocalypse("apc"), SeventhEdition("7ed"), Planeshift("pls"), ArenaLeague2001("pal01"), FridayNightMagic2001("f01"),
  JudgeGiftCards2001("g01"), MagicPlayerRewards2001("mpr"), Invasion("inv"), BeatdownBoxSet("btd"),
  WorldChampionshipDecks2000("wc00"), Prophecy("pcy"), Starter2000("s00"), Nemesis("nem"), EuropeanLandProgram("pelp"),
  ArenaLeague2000("pal00"), FridayNightMagic2000("fnm"), JudgeGiftCards2000("g00"), JuniorSuperSeries("psus"),
  BattleRoyaleBoxSet("brb"), MercadianMasques("mmq"), WizardsoftheCoastOnlineStore("pwos"), Worlds("pwor"),
  WorldChampionshipDecks1999("wc99"), Guru("pgru"), Starter1999("s99"), UrzasDestiny("uds"), PortalThreeKingdoms("ptk"),
  ClassicSixthEdition("6ed"), UrzasLegacy("ulg"), ArenaLeague1999("pal99"), JudgeGiftCards1999("g99"),
  Anthologies("ath"), UrzasSaga("usg"), AsiaPacificLandProgram("palp"), WorldChampionshipDecks1998("wc98"),
  UngluedTokens("tugl"), Unglued("ugl"), Exodus("exo"), PortalSecondAge("p02"), Stronghold("sth"),
  JudgeGiftCards1998("jgp"), Tempest("tmp"), PrereleaseEvents("ppre"), WorldChampionshipDecks1997("wc97"),
  Weatherlight("wth"), Portal("por"), VanguardSeries("pvan"), PortalDemoGame("ppod"), FifthEdition("5ed"),
  Visions("vis"), IntroductoryTwoPlayerSet("itp"), MultiverseGiftBox("mgb"), Mirage("mir"), RedemptionProgram("pred"),
  CelebrationCards("pcel"), ArenaLeague1996("parl"), RivalsQuickStartSet("rqs"), Alliances("all"),
  ProTourCollectorSet("ptc"), Homelands("hml"), Renaissance("ren"), Rinascimento("rin"), Chronicles("chr"),
  IceAge("ice"), FourthEditionForeignBlackBorder("4bb"), FourthEdition("4ed"), DCILegendMembership("plgm"),
  MagazineInserts("pmei"), FallenEmpires("fem"), HarperPrismBookPromos("phpr"), TheDark("drk"), DragonCon("pdrc"),
  SummerMagicEdgar("sum"), Legends("leg"), ForeignBlackBorder("fbb"), RevisedEdition("3ed"), Antiquities("atq"),
  ArabianNights("arn"), IntlCollectorsEdition("cei"), CollectorsEdition("ced"), UnlimitedEdition("2ed"),
  LimitedEditionBeta("leb"), LimitedEditionAlpha("lea");

  private String set = "";

  SetDBEnum(final String set) {
    this.set = set;
  }

  @Override
  public String toString() {
    return set;
  }
}
